/**
 * Arena construction.
 *
 * The shell mesh is generated by projecting a subdivided cube outward onto the
 * collision SDF, so the geometry you see is exactly the geometry you hit --
 * including the rounded floor-to-wall and wall-to-ceiling transitions. Nothing
 * is authored by hand or imported; there are no external assets in this project.
 *
 * Everything is built in the physics frame (Z up, 1 unit = 1 uu), so no
 * conversion layer is needed between simulation and render.
 */

import * as THREE from 'three';
import {
  BACK_NET_Y,
  BACK_WALL_Y,
  BOOST_PADS,
  CEILING_Z,
  GOAL_CENTER_TO_POST,
  GOAL_HEIGHT,
  SIDE_WALL_X,
  TEAM_COLORS,
} from '../core/constants';
import { V } from '../core/math';
import { field } from '../physics/field';
import { PALETTE } from './palette';

/** Where rays are cast from when projecting the shell. Arena centroid. */
const SHELL_ORIGIN = V.make(0, 0, CEILING_Z / 2);
/** Subdivision per cube face. 48 gives smooth fillets at ~28k triangles. */
const SHELL_SEGMENTS = 48;

/**
 * Build the arena shell by pushing every vertex of a subdivided cube out to the
 * collision surface along its own direction from the centre. The playfield is
 * convex, so this is well defined everywhere and lands each vertex exactly on
 * the surface.
 */
function buildShellGeometry(): THREE.BufferGeometry {
  const geo = new THREE.BoxGeometry(2, 2, 2, SHELL_SEGMENTS, SHELL_SEGMENTS, SHELL_SEGMENTS);
  const pos = geo.attributes.position as THREE.BufferAttribute;
  const normals = new Float32Array(pos.count * 3);
  const heights = new Float32Array(pos.count);

  for (let i = 0; i < pos.count; i++) {
    const dir = V.normalize(V.make(pos.getX(i), pos.getY(i), pos.getZ(i)));
    const t = field.shellDistance(SHELL_ORIGIN, dir);
    const p = V.addScaled(SHELL_ORIGIN, dir, t);
    pos.setXYZ(i, p.x, p.y, p.z);

    // Inward normal straight from the SDF: the fillets shade perfectly smooth
    // without any averaging.
    const q = field.queryShell(V.addScaled(p, dir, -1));
    normals[i * 3] = q.normal.x;
    normals[i * 3 + 1] = q.normal.y;
    normals[i * 3 + 2] = q.normal.z;
    heights[i] = p.z;
  }

  geo.setAttribute('normal', new THREE.BufferAttribute(normals, 3));
  geo.setAttribute('shellHeight', new THREE.BufferAttribute(heights, 1));
  pos.needsUpdate = true;
  geo.computeBoundingSphere();
  return geo;
}

/**
 * Shell material: a dark indigo gradient with faint horizontal ribs, so walls
 * read as a structure rather than a flat void and give the eye something to
 * judge speed against.
 */
function shellMaterial(): THREE.Material {
  const mat = new THREE.MeshStandardMaterial({
    color: PALETTE.shellMid,
    roughness: 0.85,
    metalness: 0.1,
    side: THREE.BackSide,
    // A faint self-lit floor keeps the corner fillets and the base of the
    // walls from reading as black holes when they face away from the key light.
    emissive: PALETTE.shellDeep,
    emissiveIntensity: 0.85,
  });

  mat.onBeforeCompile = (shader) => {
    shader.uniforms.uDeep = { value: new THREE.Color(PALETTE.shellDeep) };
    shader.uniforms.uRib = { value: new THREE.Color(PALETTE.shellRib) };
    shader.vertexShader = shader.vertexShader
      .replace('#include <common>', '#include <common>\nattribute float shellHeight;\nvarying float vShellHeight;')
      .replace('#include <begin_vertex>', '#include <begin_vertex>\nvShellHeight = shellHeight;');
    shader.fragmentShader = shader.fragmentShader
      .replace(
        '#include <common>',
        '#include <common>\nuniform vec3 uDeep;\nuniform vec3 uRib;\nvarying float vShellHeight;',
      )
      .replace(
        '#include <color_fragment>',
        `#include <color_fragment>
        float h = clamp(vShellHeight / ${CEILING_Z.toFixed(1)}, 0.0, 1.0);
        vec3 base = mix(uDeep, diffuseColor.rgb, smoothstep(-0.4, 0.8, h));
        float rib = smoothstep(0.86, 1.0, abs(sin(vShellHeight * 0.0295)));
        diffuseColor.rgb = mix(base, uRib, rib * 0.5 * smoothstep(0.02, 0.25, h));`,
      );
  };
  return mat;
}

/** Field markings, drawn to a canvas rather than shipped as an image. */
function buildFloorTexture(): THREE.CanvasTexture {
  const w = 1024;
  const h = 1280; // matches the 8192 x 10240 field ratio
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d')!;

  const grad = ctx.createLinearGradient(0, 0, 0, h);
  grad.addColorStop(0, '#1e2450');
  grad.addColorStop(0.5, '#2a3170');
  grad.addColorStop(1, '#1e2450');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, w, h);

  // Mown stripes down the long axis.
  ctx.fillStyle = 'rgba(255,255,255,0.05)';
  for (let i = 0; i < 10; i += 2) ctx.fillRect((i * w) / 10, 0, w / 10, h);

  ctx.strokeStyle = 'rgba(233,240,255,0.95)';
  ctx.lineWidth = 4;
  ctx.strokeRect(6, 6, w - 12, h - 12);

  // Halfway line and centre circle.
  ctx.beginPath();
  ctx.moveTo(0, h / 2);
  ctx.lineTo(w, h / 2);
  ctx.stroke();
  ctx.beginPath();
  ctx.arc(w / 2, h / 2, w * 0.14, 0, Math.PI * 2);
  ctx.stroke();
  ctx.beginPath();
  ctx.arc(w / 2, h / 2, 8, 0, Math.PI * 2);
  ctx.fillStyle = 'rgba(233,240,255,0.9)';
  ctx.fill();

  // Goal areas, tinted per team.
  const boxW = w * 0.42;
  const boxH = h * 0.12;
  for (const [i, color] of [
    [0, 'rgba(24,224,255,0.3)'],
    [1, 'rgba(255,47,164,0.3)'],
  ] as const) {
    const y = i === 0 ? h - boxH - 6 : 6;
    ctx.fillStyle = color;
    ctx.fillRect((w - boxW) / 2, y, boxW, boxH);
    ctx.strokeStyle = i === 0 ? 'rgba(24,224,255,0.8)' : 'rgba(255,47,164,0.8)';
    ctx.strokeRect((w - boxW) / 2, y, boxW, boxH);
  }

  // Corner arcs.
  ctx.strokeStyle = 'rgba(233,240,255,0.7)';
  ctx.lineWidth = 3;
  for (const [cx, cy, a0] of [
    [6, 6, 0],
    [w - 6, 6, Math.PI / 2],
    [w - 6, h - 6, Math.PI],
    [6, h - 6, -Math.PI / 2],
  ] as const) {
    ctx.beginPath();
    ctx.arc(cx, cy, w * 0.06, a0, a0 + Math.PI / 2);
    ctx.stroke();
  }

  const tex = new THREE.CanvasTexture(canvas);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.anisotropy = 8;
  return tex;
}

function buildFloor(): THREE.Mesh {
  const geo = new THREE.PlaneGeometry(SIDE_WALL_X * 2, BACK_WALL_Y * 2);
  const texture = buildFloorTexture();
  const mat = new THREE.MeshStandardMaterial({
    map: texture,
    // The same texture drives a low-level emissive so the markings stay
    // readable in the shadowed half of the pitch instead of going black.
    emissiveMap: texture,
    emissive: 0xffffff,
    emissiveIntensity: 0.3,
    roughness: 0.92,
    metalness: 0.02,
    // The shell also covers the floor, a couple of units below this plane. At
    // grazing angles right in front of the camera that gap is smaller than the
    // depth buffer can resolve, so pull the markings forward explicitly.
    polygonOffset: true,
    polygonOffsetFactor: -4,
    polygonOffsetUnits: -8,
  });
  const mesh = new THREE.Mesh(geo, mat);
  // Plane geometry faces +Z already, which is up in our frame. Lift it a hair
  // so it wins the depth fight with the shell.
  mesh.position.z = 2.5;
  mesh.receiveShadow = true;
  return mesh;
}

/** Goal recess: a dark box with a glowing frame and a net-like backdrop. */
function buildGoal(side: -1 | 1): THREE.Group {
  const group = new THREE.Group();
  const team = side < 0 ? 0 : 1;
  const color = TEAM_COLORS[team];
  const depth = BACK_NET_Y - BACK_WALL_Y;
  const width = GOAL_CENTER_TO_POST * 2;

  const interior = new THREE.Mesh(
    new THREE.BoxGeometry(width, depth, GOAL_HEIGHT),
    new THREE.MeshStandardMaterial({
      color: 0x0a0b1c,
      roughness: 1,
      side: THREE.BackSide,
    }),
  );
  interior.position.set(0, side * (BACK_WALL_Y + depth / 2), GOAL_HEIGHT / 2);
  group.add(interior);

  // Netting: a grid of thin lines on the back face, cheap and reads correctly.
  const netMat = new THREE.LineBasicMaterial({ color, transparent: true, opacity: 0.32 });
  const pts: number[] = [];
  const y = side * (BACK_NET_Y - 4);
  for (let i = 0; i <= 16; i++) {
    const x = -GOAL_CENTER_TO_POST + (width * i) / 16;
    pts.push(x, y, 0, x, y, GOAL_HEIGHT);
  }
  for (let i = 0; i <= 8; i++) {
    const z = (GOAL_HEIGHT * i) / 8;
    pts.push(-GOAL_CENTER_TO_POST, y, z, GOAL_CENTER_TO_POST, y, z);
  }
  const netGeo = new THREE.BufferGeometry();
  netGeo.setAttribute('position', new THREE.Float32BufferAttribute(pts, 3));
  group.add(new THREE.LineSegments(netGeo, netMat));

  // Frame: posts and crossbar, emissive so the mouth reads at a distance.
  const frameMat = new THREE.MeshStandardMaterial({
    color,
    emissive: color,
    emissiveIntensity: 1.4,
    roughness: 0.4,
  });
  const postGeo = new THREE.CylinderGeometry(22, 22, GOAL_HEIGHT, 12);
  for (const sx of [-1, 1]) {
    const post = new THREE.Mesh(postGeo, frameMat);
    // Cylinders are Y-aligned; stand it up in our Z-up frame.
    post.rotation.x = Math.PI / 2;
    post.position.set(sx * GOAL_CENTER_TO_POST, side * BACK_WALL_Y, GOAL_HEIGHT / 2);
    group.add(post);
  }
  const bar = new THREE.Mesh(new THREE.CylinderGeometry(22, 22, width, 12), frameMat);
  bar.rotation.z = Math.PI / 2;
  bar.position.set(0, side * BACK_WALL_Y, GOAL_HEIGHT);
  group.add(bar);

  return group;
}

export interface PadVisual {
  mesh: THREE.Object3D;
  glow: THREE.Mesh;
  big: boolean;
}

/**
 * Boost pads. Big pads are tall hexagonal pillars of light, small pads are flat
 * discs, so the two read differently at a glance and from across the field.
 */
function buildPads(): { group: THREE.Group; visuals: PadVisual[] } {
  const group = new THREE.Group();
  const visuals: PadVisual[] = [];

  // Cylinders are built Y-aligned. Rotate the GEOMETRY (not the mesh) so the
  // pad's axis is world up and the spin animation can use plain Z rotation --
  // spinning a mesh that carries its own X rotation just tips the pillar over.
  const bigGeo = new THREE.CylinderGeometry(90, 110, 190, 6, 1, true);
  bigGeo.rotateX(Math.PI / 2);
  const smallGeo = new THREE.CylinderGeometry(58, 70, 26, 6);
  smallGeo.rotateX(Math.PI / 2);
  const bigMat = new THREE.MeshStandardMaterial({
    color: PALETTE.boostBig,
    emissive: PALETTE.boostBig,
    emissiveIntensity: 1.1,
    transparent: true,
    opacity: 0.55,
    side: THREE.DoubleSide,
  });
  const smallMat = new THREE.MeshStandardMaterial({
    color: PALETTE.boost,
    emissive: PALETTE.boost,
    emissiveIntensity: 0.9,
    transparent: true,
    opacity: 0.8,
  });
  const baseMat = new THREE.MeshStandardMaterial({
    color: 0x2a2f5c,
    roughness: 0.6,
    metalness: 0.3,
  });

  for (const spec of BOOST_PADS) {
    const holder = new THREE.Group();
    holder.position.set(spec.x, spec.y, 0);

    const baseGeo = new THREE.CylinderGeometry(
      spec.big ? 120 : 76,
      spec.big ? 130 : 84,
      10,
      6,
    );
    baseGeo.rotateX(Math.PI / 2);
    const base = new THREE.Mesh(baseGeo, baseMat);
    base.position.z = 5;
    holder.add(base);

    const glow = new THREE.Mesh(spec.big ? bigGeo : smallGeo, spec.big ? bigMat : smallMat);
    glow.position.z = spec.big ? 100 : 20;
    holder.add(glow);

    group.add(holder);
    visuals.push({ mesh: holder, glow, big: spec.big });
  }

  return { group, visuals };
}

/**
 * Crowd: a banked band of dim points, seated high on the inside face of the
 * shell so they read as spectators behind the glass.
 *
 * They have to be *inside* the shell to be seen at all -- the arena is a closed
 * volume, so anything outside it is occluded from every angle a player can
 * reach. Placement follows the real outline via the same SDF the collision
 * uses, rather than an ellipse: an ellipse looks right until you notice its
 * diagonals cut inside the chamfered corners and seat a few thousand
 * spectators on the pitch.
 */
function buildCrowd(): THREE.Points {
  const count = 9000;
  const positions = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3);
  const base = new THREE.Color(PALETTE.crowd);

  for (let i = 0; i < count; i++) {
    const bearing = Math.random() * Math.PI * 2;
    const tier = Math.random();
    const z = 1180 + tier * 700 + Math.random() * 40;

    const dir = V.make(Math.cos(bearing), Math.sin(bearing), 0);
    const wall = field.shellDistance(V.make(0, 0, z), dir);
    // Just inside the wall face, tiered back as the rows climb.
    const radius = wall - 30 - tier * 150;

    positions[i * 3] = dir.x * radius;
    positions[i * 3 + 1] = dir.y * radius;
    positions[i * 3 + 2] = z;

    const c = base.clone().offsetHSL((Math.random() - 0.5) * 0.16, 0, (Math.random() - 0.5) * 0.42);
    colors[i * 3] = c.r;
    colors[i * 3 + 1] = c.g;
    colors[i * 3 + 2] = c.b;
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
  geo.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
  return new THREE.Points(
    geo,
    new THREE.PointsMaterial({ size: 26, vertexColors: true, sizeAttenuation: true }),
  );
}

/** Sky: a vertical gradient dome with a warm glow near the horizon. */
function buildSky(): THREE.Mesh {
  const geo = new THREE.SphereGeometry(24000, 32, 20);
  const mat = new THREE.ShaderMaterial({
    side: THREE.BackSide,
    depthWrite: false,
    uniforms: {
      uTop: { value: new THREE.Color(PALETTE.skyTop) },
      uHorizon: { value: new THREE.Color(PALETTE.skyHorizon) },
      uGlow: { value: new THREE.Color(PALETTE.skyGlow) },
    },
    vertexShader: `
      varying vec3 vDir;
      void main() {
        vDir = normalize(position);
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }`,
    fragmentShader: `
      uniform vec3 uTop; uniform vec3 uHorizon; uniform vec3 uGlow;
      varying vec3 vDir;
      void main() {
        float h = clamp(vDir.z * 0.5 + 0.5, 0.0, 1.0);
        vec3 col = mix(uHorizon, uTop, smoothstep(0.5, 0.92, h));
        // Warm flare low on one side, so the arena has a light direction.
        float flare = pow(max(0.0, dot(normalize(vDir), normalize(vec3(0.35, -0.85, 0.12)))), 8.0);
        col += uGlow * flare * 0.5;
        col = mix(col, uHorizon * 1.3, smoothstep(0.55, 0.42, h));
        gl_FragColor = vec4(col, 1.0);
      }`,
  });
  return new THREE.Mesh(geo, mat);
}

export interface Arena {
  group: THREE.Group;
  pads: PadVisual[];
  goalRings: THREE.Object3D[];
}

export function buildArena(scene: THREE.Scene): Arena {
  const group = new THREE.Group();

  const shell = new THREE.Mesh(buildShellGeometry(), shellMaterial());
  shell.receiveShadow = true;
  group.add(shell);
  group.add(buildFloor());

  const goalRings: THREE.Object3D[] = [];
  for (const side of [-1, 1] as const) {
    const goal = buildGoal(side);
    goalRings.push(goal);
    group.add(goal);
  }

  const { group: padGroup, visuals } = buildPads();
  group.add(padGroup);
  group.add(buildCrowd());
  group.add(buildSky());

  // Stadium lighting: a cool ambient fill, a warm key from one corner, and rim
  // lights over each goal in that team's colour.
  scene.add(new THREE.HemisphereLight(0xbcd0ff, 0x2a2450, 1.25));
  // A dim ambient floor so nothing in the arena ever reads as pure black.
  scene.add(new THREE.AmbientLight(0x6c76b4, 0.3));

  const key = new THREE.DirectionalLight(0xfff0dd, 1.9);
  key.position.set(2600, -4200, 3600);
  key.castShadow = true;
  key.shadow.mapSize.set(1536, 1536);
  key.shadow.camera.near = 500;
  key.shadow.camera.far = 14000;
  const s = 6200;
  key.shadow.camera.left = -s;
  key.shadow.camera.right = s;
  key.shadow.camera.top = s;
  key.shadow.camera.bottom = -s;
  key.shadow.bias = -0.0006;
  scene.add(key);
  scene.add(key.target);

  // A soft counter-light from the far corner keeps the shadow side legible.
  const fill = new THREE.DirectionalLight(0xa8c0ff, 0.9);
  fill.position.set(-3000, 4500, 2400);
  scene.add(fill);

  for (const [i, side] of [-1, 1].entries()) {
    const rim = new THREE.PointLight(TEAM_COLORS[i], 4.5, 8000, 1.5);
    rim.position.set(0, side * (BACK_WALL_Y - 500), 800);
    scene.add(rim);
  }

  scene.add(group);
  return { group, pads: visuals, goalRings };
}
